dbSQLCollector/oracle_db_assessment.sql

Changed SQL format.
BugFix in some CSVs the column con_id is coming out #### due to poor SQL column format

Bug fix with con_id column being # in CSVs files

---

dbSQLCollector/oracle_db_assessment.sql
dbSQLCollector/oracle_db_assessment_11g.sql

add database services information and user schemas with segments in SYSTEM and SYSAUX

 add database services information and user schemas with segments in SYSTEM and SYSAUX 

---

db-assessment/dbSQLCollector/oracle_db_assessment.sql
db-assessment/dbSQLCollector/oracle_db_assessment_11g.sql

Update of spool file name format and changes (additional columns column format) to both scripts.

update spool format and add columns

---

db_assessment/dbSQLCollector/oracle_db_assessment_12c_AND_ABOVE.sql

Removed the type from the script.

Bugfix: Script had a typo

---

db_assessment/dbSQLCollector/oracle_db_assessment_12c_AND_ABOVE.sql
db_assessment/dbSQLCollector/oracle_db_assessment_ONLY_FOR_11g.sql

Bug fix for AWS OS Stats dictionary view

bugfix awr osstat

---

README.md

I was not sure if Step mentioned is Actually "Step 3" or "1.3"

Updated step numbers

---

db_assessment/optimusprime.py

collectionversion is the correct user argument. optimuscollectionversion is internal variable name , so corrected the message accordingly

Issue68 - Fix error message

---

db_assessment/dbSQLCollector/assessment_wrapper.sql

Updated Licensing Text

---

db_assessment/opConfig/transformers.json

Minor update to the transformer.json file to equalize with the new version of SQL scripts (2.0.4).

smj-op_tjson_upd

---

README.md

added keyword project keyword in
gcloud config set project <project id>

added project keyword

---

cloudbuild.yaml
db_assessment/api.py
db_assessment/optimusprime.py
db_assessment/remote.py
db_assessment/set_client_info.py
tasks.py

Leveraging the API to load into BQ

Adding remote api calls to optimusprime

---

db_assessment/import_db_assessment.py
db_assessment/optimusprime.py
db_assessment/rules_engine.py

Added support to -sep flag to change how OP handles file separator

---

db_assessment/api.py

Add new args to api definition enabling build to pass 

---

db_assessment/import_db_assessment.py

Track Optimus Prime usage by calling client INFO API for every DB import

---

db_assessment/import_db_assessment.py
db_assessment/optimusprime.py
db_assessment/rules_engine.py

Reverts GoogleCloudPlatform/oracle-database-assessment#134

Revert "Origin/add flags skip data load"

---

README.md

Create a Table in Git with OP tables and description

---

db_assessment/import_db_assessment.py

Removed harcoded Elapsed time condition in populateBT function

---

.gitignore
Dockerfile
api-requirements.txt
db_assessment/api.py
db_assessment/import_db_assessment.py
db_assessment/optimusprime.py
db_assessment/remote.py
db_assessment/rules_engine.py
db_assessment/set_client_info.py
setup.py
tasks.py

Reverts GoogleCloudPlatform/oracle-database-assessment#166
Documentation needs to be updated to reflect the new python modules.  Rolling back until documentation reflects the correct steps to execute.

Revert "ER: Hardened Docker Build. "

---

db_assessment/opConfig/transformers.json
db_assessment/op_etl_template.sql
deploy/docker/cloudbuild/Dockerfile
scripts/4_gen_op_report_url.sh

Update to the Big Query ETL code to support a new chart in the Data Studio template.

Report update 20221026

---

.bumpversion.cfg
Makefile
README.md
docs/index.md
scripts/collector/oracle/README.txt
scripts/collector/oracle/collect-data.sh

This update incorporates all of the latest collection script changes required for Database Migration Assessment

Version 4.0

---

scripts/collector/oracle/collect-data.sh
scripts/collector/oracle/sql/extracts/dbparameters.sql
scripts/collector/oracle/sql/extracts/pdbsinfo.sql
scripts/collector/oracle/sql/op_collect_init.sql

Address issue uncovered in 12.1.0.1 release of Oracle.

fix: address issue cased by model variation in Oracle sys schemas in 12.1.0.1

---

docs/user_guide/oracle/collection_scripts.md

Adjust wording on collection scripts instructions.

docs: updated instructions

---

docs/user_guide/sqlserver/collection_scripts.md
docs/user_guide/sqlserver/db_user_create.md

Update documentation to reflect the proper execution of the scripts for sql sercer.

Update sql server documentation

---

.github/ISSUE_TEMPLATE/bug report.yaml
.github/ISSUE_TEMPLATE/document.yaml
.github/ISSUE_TEMPLATE/enhancement request.yaml
.github/ISSUE_TEMPLATE/new feature.yaml

Updated the templates so that everything comes in as un-assigned.

feat: Remove default assignee

---

README.md
docs/user_guide/sqlserver/collection_scripts.md
scripts/collector/sqlserver/ManageSqlServerPerfmonDataset.bat
scripts/collector/sqlserver/README.txt
scripts/collector/sqlserver/createuserwithsqluser.ps1
scripts/collector/sqlserver/sql/ServerProperties.sql
scripts/collector/sqlserver/sql/objectList.sql

Updated scripts to allow for powershell bypass execution policy.  Also updated documents to limit scripts to SQL 2017

Mssql fixes

---

scripts/collector/sqlserver/InstanceReview.ps1
scripts/collector/sqlserver/dma_sqlserver_perfmon_dataset.ps1
scripts/collector/sqlserver/sql/ServerProperties.sql
scripts/collector/sqlserver/sql/dbccTraceFlags.sql
scripts/collector/sqlserver/sql/diskVolumeInfo.sql
scripts/collector/sqlserver/sql/objectList.sql

Add additional server properties queries in order to satisfy the initial implementation of the assessment model

Mssql collector additions

---

scripts/collector/sqlserver/CreateUserForAssessmentWithSQLAuth.bat
scripts/collector/sqlserver/CreateUserForAssessmentWithWindowsAuth.bat
scripts/collector/sqlserver/ManageSqlServerPerfmonDataset.bat
scripts/collector/sqlserver/RunAssessment.bat
scripts/collector/sqlserver/createuserwithsqluser.ps1
scripts/collector/sqlserver/createuserwithwindowsauth.ps1
scripts/collector/sqlserver/sql/ComponentsInstalled.sql
scripts/collector/sqlserver/sql/Features.sql
scripts/collector/sqlserver/sql/LinkedServers.sql
scripts/collector/sqlserver/sql/ServerProperties.sql
scripts/collector/sqlserver/sql/columnDatatypes.sql
scripts/collector/sqlserver/sql/dbClusterNodes.sql
scripts/collector/sqlserver/sql/dbSizes.sql
scripts/collector/sqlserver/sql/dbccTraceFlags.sql
scripts/collector/sqlserver/sql/diskVolumeInfo.sql
scripts/collector/sqlserver/sql/foldername.sql
scripts/collector/sqlserver/sql/indexList.sql
scripts/collector/sqlserver/sql/objectList.sql
scripts/collector/sqlserver/sql/prereq_createsa.sql
scripts/collector/sqlserver/sql/tableList.sql
scripts/collector/sqlserver/sql/userConnectionInfo.sql

- Fixed quotations around help text
- Fixed convert datatype functionality

Sql server 4.3.5 quickfix

---

docs/user_guide/oracle/collection_masker.md

Change the case on the markdown section title.

docs: formatting change

---

.bumpversion.cfg
scripts/collector/oracle/collect-data.sh
scripts/collector/sqlserver/createUserWithSQLAuth.ps1
scripts/collector/sqlserver/createUserWithWindowsAuth.ps1
scripts/collector/sqlserver/instanceReview.ps1
scripts/collector/sqlserver/sql/addCollectionUserPermissions.sql
scripts/collector/sqlserver/sql/createCollectionUser.sql
scripts/collector/sqlserver/sql/dropCollectionUser.sql
scripts/masker/dma-collection-masker

fix: bug 299460067 - Update syntax for sql server versions < 2022
feat: Add functionality to drop collection user
feat: Add script to add collection permissions to an existing user

feat: updates to MSSQL user create process

---

docs/user_guide/oracle/collection_scripts.md

Corrected parameter list documentation for connecting as sysdba.

Corrected parameter list documentation for connecting as sysdba.

---

.bumpversion.cfg
scripts/collector/mysql/collect-data.sh
scripts/collector/oracle/collect-data.sh
scripts/collector/postgres/collect-data.sh
scripts/collector/sqlserver/instanceReview.ps1
scripts/masker/dma-collection-masker

Support the version of sed that is available in HP-UX.

feat: HP-UX support

---

scripts/collector/sqlserver/instanceReview.ps1

Update -managedInstanceName to -namedInstanceName

---

scripts/collector/mysql/collect-data.sh
scripts/collector/postgres/collect-data.sh

Add error capture and handling to Postgres collector.

feat: Postgres error handling

---

scripts/collector/sqlserver/sql/indexList.sql

I verified this in our MSSQL database. 
There were 2 indexes from views that had null schemas.
i added the logic to add schema_name to views (that have schema_id)
then if the s.NAME is null, take v.schema_name (like table_name)

fix: `MSSQL` Suggestion to fix null schemaName when the table is a view

---

scripts/collector/mysql/db-machine-specs.sh

see https://github.com/GoogleCloudPlatform/database-assessment/pull/332

feat: `mysql` Update db-machine-specs.sh - changed disk used/total to real number

---

scripts/collector/sqlserver/README.txt
scripts/collector/sqlserver/dmaSQLServerHWSpecs.ps1
scripts/collector/sqlserver/instanceReview.ps1
scripts/collector/sqlserver/runAssessment.bat

Reverts GoogleCloudPlatform/database-assessment#317

revert: feat: Adding remote Windows params for WMI-GetObject

---

scripts/collector/mysql/collect-data.sh

* Capture MySQL error output to a file.

feat: Capture MySQL error output to a file.

---

scripts/collector/sqlserver/sql/serverProperties.sql

Fix statement with missing parenthesis

fix: syntax error with exec statement

---

.github/workflows/release.yaml

Reverting this change as it needs some work.

fix: revert hashing actions

---

scripts/collector/mysql/collect-data.sh

* Better error handling when unable to connect to the target database.
* Clarify error message if incorrect number of parameters supplied.
* Sync with Postgres branch

fix: `mysql` error message updates

---

scripts/collector/sqlserver/sql/dbServerFeatures.sql

fix: rollup and remove duplicate permission detection

fix: remove duplicate values from `mssql` features list

---

scripts/collector/mysql/collect-data.sh

* Address https://buganizer.corp.google.com/issues/325157367

feat: Add entry for `manualUniqueId` parameter to help text for `mysql`

---

scripts/collector/postgres/collect-data.sh

* Address https://buganizer.corp.google.com/issues/325157367

feat: Add entry for `manualUniqueId` parameter to help text for `postgres`

---

scripts/collector/mysql/README.txt
scripts/collector/postgres/README.txt

* Update READMEs for Postgres and MySQL.

feat: Update READMEs for `Postgres` and `MySQL`.

---

Makefile

* Add Postgres SQL subdirectories to ZIP packaging.

fix: Add Postgres SQL subdirectories to ZIP packaging.

---

docs/user_guide/mysql/collection_scripts.md
docs/user_guide/postgres/collection_scripts.md
scripts/collector/mysql/README.txt
scripts/collector/postgres/README.txt

* Add markdown docs for Postgres and MySql.
* Update README.txt to match markdown files.

chore: Add documentation for Postgres and MySql.

---

scripts/collector/postgres/collect-data.sh

Fix issue with mismatched machine_specs file during recursive collection.

fix: handle `machine_specs` for multi-database collection

---

scripts/collector/mysql/sql/config.sql

* Remove the schema grouping in config.sql.

fix: Granularity change for database-level `mqsql` stats

---

scripts/collector/postgres/collect-data.sh

* Change method of extracting list of all databases.
* Do not display Postgres connection string in error.

feat: update `postgres` database list method

---

docs/user_guide/oracle/collection_scripts.md
scripts/collector/oracle/README.txt

* Update the README and and markdown documents with separate examples for CDB and non-CDB databases.

chore(docs): Add separate examples for CDB and non-CDB databases.

---

docs/user_guide/postgres/collection_scripts.md
scripts/collector/postgres/README.txt
scripts/collector/postgres/collect-data.sh

chore(docs): Updated documentation to reflect use of flag --allDbs.

---

docs/user_guide/mysql/collection_scripts.md

This fixes a typo in supported versions

docs: Updated typo for supported versions

---

scripts/collector/mysql/collect-data.sh
scripts/collector/mysql/sql/hostname.sql
scripts/collector/postgres/db-machine-specs.sh
scripts/collector/postgres/sql/12/database_details.sql
scripts/collector/postgres/sql/12/replication_slots.sql
scripts/collector/postgres/sql/13/database_details.sql
scripts/collector/postgres/sql/13/replication_slots.sql
scripts/collector/postgres/sql/base/database_details.sql
scripts/collector/sqlserver/dmaSQLServerHWSpecs.ps1

This allows us to match the DB with the containing VM

feat: Include Primary MAC address and IP address

---

.github/workflows/release.yaml
pyproject.toml

This change updates the pyapp packager to the latest release.

chore: modify pyapp version

---

scripts/collector/postgres/sql/extensions.sql
src/dma/collector/sql/sources/postgres/collection-extensions.sql

add `is_super_user` indicator to `extensions` file

feat: extension superuser indicator

---

scripts/collector/oracle/sql/op_collect_init.sql

* Set specific size for pkey column to reduce size of intermediate files before cleanup & compression.

feat(oracle): set specific size for pkey column.

---

src/dma/collector/workflows/readiness_check/_postgres/main.py

Condense SQL strings and don't use use triple quotes (`"""`)
This allows format for syntax highlighting in VSCode.

chore(formatting): minify SQL statements

---

docs/user_guide/mysql/collection_scripts.md
docs/user_guide/postgres/collection_scripts.md

Update sql/postgres to point users to MC for homogenous migrations

docs: update note for `postgres`/`mysql `

---

scripts/collector/postgres/db-machine-specs.sh

feat: Store pkey, sourceID and manualId when machine specs fails.

---

scripts/masker/dma-collection-masker

Fixes an issue where the incorrect data type was being used in the masker metadata

fix: data type correction

---

docs/user_guide/sqlserver/collection_scripts.md
scripts/collector/sqlserver/README.txt

Update the mssql docs to show that SYSADMIN is not needed.

chore(docs): mssql documentation updates

---

Makefile

* fix(cli): Add missing $(BUILD_DIR)/collector/mysql/sql/headers to make file.

fix(mysql): adds missing headers to collection

---

src/dma/collector/query_managers.py
src/dma/collector/sql/canonical/ddls-postgres-collection.sql
src/dma/collector/sql/sources/postgres/collection-bg_writer_stats.sql

Refer https://www.postgresql.org/docs/17/release-17.html

Ignore columns removed from pg_stat_bgwriter table in pg17.

---

src/dma/collector/workflows/readiness_check/_postgres/main.py
tests/integration/postgres/test_readiness_assessment.py
tests/unit/test_collector/test_workflows/test_readiness_check/test_postgres.py

Add test cases for extensions and tables with no primary keys

Add test cases for extensions and tables with no primary keys

---

src/dma/collector/query_managers.py
src/dma/collector/sql/canonical/ddls-postgres-collection.sql
src/dma/collector/sql/sources/postgres/collection-privileges.sql
src/dma/collector/sql/sources/postgres/collection-table_details.sql
src/dma/collector/workflows/readiness_check/_postgres/main.py

Add replication role and replica identity checks

feat(cli) - add replication role and replica identity checks

---

readiness-check.md
tests/integration/postgres/northwind_data.sql
tests/integration/postgres/northwind_ddl.sql
tools/install-hatch.sh

chore: add licensing information to SQL test files and update install script

chore: add licensing header to test files

---

docs/user_guide/shell_scripts/oracle/dms_migration_job_validation.md
scripts/collector/oracle/sql/dms_migration_job_validator.sql

feat(oracle): update DMS Migration Job Validation script and docs for v1.1 release

---

docs/user_guide/shell_scripts/oracle/dms_migration_job_validation.md
scripts/collector/oracle/sql/dms_migration_job_validator.sql

* Amend wording of unsupported column names and unsupported data types checks
* Amend output of namespace clash check

feat(oracle): update DMS Migration Job Validation script and docs for v1.2 release
