GoogleCloudPlatform/database-assessment

dbSQLCollector/oracle_db_assessment.sql, dbSQLCollector/oracle_db_assessment_11g.sql
Changes to work with DBA_* views instead of CDB_* views.
Removed columns not available in older releases.
Removed order by from v$diag_alert_ext - Details at MOS Doc ID 2119059.1
=> script for older Oracle database releases

db_assessment/dbSQLCollector/oracle_db_assessment_12c_AND_ABOVE.sql, db_assessment/dbSQLCollector/oracle_db_assessment_ONLY_FOR_11g.sql, db_assessment/opConfig/transformers.json
Close #48
Bug fix for OSSTAT. Handling non incremental values. A new colum in the main query was added to keep the original value 
DBA_HIST_OSSTAT.VALUE
=> bugfix awr osstat - handling non cumulative values

db_assessment/import_db_assessment.py
There is a bug when the user is not using fromdataframe and try to load all CSVs as from source files directly. The issue is when we try to add some fields to opkeylog table and is fixed with this commit
=> Issue 71: Fixed code to avoid errors when fromdataframe is not used  

README.md
This fixes various formatting issue in markdown.
Eg. lists not being lists when rendered.
=> Fixes markdown formatting

README.md
README.md was inconsistent regarding use of "Big Query" and "BigQuery". The official name is BigQuery (no space) as shown on https://cloud.google.com/bigquery, so all uses changed to BigQuery.
=> "Big Query" -> "BigQuery" for consistency in README.md.

db_assessment/dbSQLCollector/collectData-Step1.sh
Determine where collectData-Step1.sh is located place path into SCRIPT_DIR and then derive BASE_DIR from that.  This allows you to run the script from anywhere and continue to have correct relative paths.
=> PR: Introduce SCRIPT_DIR var in order to derive BASE_DIR

scripts/collector/oracle/collect-data.sh, scripts/collector/oracle/sql/op_collect_init.sql
Allow extraction without performance data if NoDiagnostics flag is passed and there is no STATSPACK data.
=> Prevent extraneous "*csv" file generation on error.

.github/workflows/ci.yaml, .github/workflows/docs.yaml, .github/workflows/release.yaml
This PR bumps the checkout actions to `v4`.
=> ci: bump github checkout actions to v4

Makefile
This PR correct the spelling of the postgres zip file.
=> ci: correct spelling of postgres package

.bumpversion.cfg, scripts/collector/mysql/collect-data.sh, scripts/collector/oracle/README.txt, scripts/collector/oracle/collect-data.sh, scripts/collector/postgres/collect-data.sh, scripts/collector/sqlserver/instanceReview.ps1, scripts/masker/dma-collection-masker
Correct misspelling of parameter controlling STATSPACK access.
Update README.txt with correct parameter names and examples, to match  the docs.
=> fix: correct STATSPACK parameter name

scripts/collector/sqlserver/dmaSQLServerHWSpecs.ps1, scripts/collector/sqlserver/instanceReview.ps1
dmaSQLServerHWSpecs.ps1 collects amount of cores and total memory capacity in bytes from the machineName
in SQL collect script.
I've tested it on 2 labs, it has a prerequisite of access of WMI from where the script is being run, if it fails it should only log a failure and not fail the collection script.
I've ran the `make build`
then copied the zip into a windows machine and ran it against another windows machine with MSSQL server
output csv:
```
"pkey"|"dma_source_id"|"dma_manual_id"|"computer_name"|"cores"|"memory_bytes"
"WIN-U6S28Q6HGOB_master_MSSQLSERVER_102923052805"|"WIN-U6S28Q6HGOB_33758EFA592E405990C30073089AD701_MSSQLSERVER"|"NA"|"WIN-U6S28Q6HGOB"|"4"|"8589934592"
```
=> feat: Adding dmaSQLServerHWSpecs.ps1 to collect the HW Shape info

docs/user_guide/sqlserver/collection_scripts.md, scripts/collector/sqlserver/README.txt, scripts/collector/sqlserver/dmaSQLServerPerfmonDataset.ps1
change includes:
1. Added two metrics to the PerfMon collection script: 
a. `NUMA Node Memory(_Total)\Total MBytes`
b. `NUMA Node Memory(_Total)\Available MBytes`
2. Fixing the collection script to work directly by setting `$perfmonOutFile` if its not set
=> Perfmon - Adding Memory from NUMA Node Memory(_Total)

scripts/collector/postgres/db-machine-specs.sh
It was of the form: 2.08914e+10
so i modified it to use printf(%.0f)
which prints it in real number
=> fix: `postgres` db-machine-specs.sh - change disk used/total to long values

docs/user_guide/oracle/collection_scripts.md, scripts/collector/oracle/collect-data.sh, scripts/collector/oracle/sql/op_collect.sql, scripts/collector/oracle/sql/op_collect_init.sql
This PR does the following Oracle changes:
- Add option limit `AWR` collection window of performance stats to 7 days.
- Use 'N/A' for md5 hash in manifest file if `md5sum` binary is not installed.
- Suppress error message if md5sum is not installed.
- Change method of checking user privileges.
- Remove parenthesis for ksh compatibility.
=> feat: `AIX` related fixes and manually limit `AWR` usage period

docs/user_guide/sqlserver/collection_scripts.md, scripts/collector/sqlserver/README.txt, scripts/collector/sqlserver/dmaSQLServerHWSpecs.ps1, scripts/collector/sqlserver/runAssessment.bat
We first try to collect using current user credentials. If that fails, and the user has set the -collectVMSpecs flag, we request the credentials from the user via a pop up prompt:
We also slightly modify the existing script to write machine name to csv even on failure.
=> feat: Add option to request user credentials when collecting HW specs (windows)

.github/workflows/release.yaml
This PR adds an file called `hashes.txt` to each release.  This file contains the `SHA256` checksums for the files at the time they were packaged.
=> chore: adds hashes to release

docker-compose.yml, scripts/collector/mysql/sql/config.sql, scripts/collector/mysql/sql/data_types.sql, scripts/collector/mysql/sql/database_details.sql, scripts/collector/mysql/sql/engines.sql, scripts/collector/mysql/sql/plugins.sql, scripts/collector/mysql/sql/schema_objects.sql, scripts/collector/mysql/sql/table_details.sql, scripts/collector/mysql/sql/users.sql
This PR removes all common table expressions from the MySQL collector scripts.
This enables support for older releases of MySQL and Percona
=> feat: remove `cte` expressions for older `mysql` support

docs/user_guide/oracle/collection_masker.md, requirements.txt, scripts/masker/dma-collection-masker
This PR adds column masking for
- PKEY
- DMA_SOURCE_ID
- hostname
- database name
- instance name
It also masks the collection key in both the archive file and the CSV files within the archive and keeps this key consistent between the two.
In dealing with `PKEY` and `DMA_SOURCE_ID` masking I added wildcard functionality to apply to all files.
I've reviewed the Oracle canonical tables and added the columns that need to be masked.
I wasn't sure if the **oracle_dataguard** table might have some hostname info in the connect string that might need to be looked at. I haven't dealt with this here.
I've manually tested this as far as possible but it does need more testing by another person IMO.
Finally, there are some formatting and minor changes from running the ruff linter and formatter over …
=> feat: column masking additions and file name masking

scripts/masker/dma-collection-masker
This PR change 2 type hints to the 3.8 style syntax.
`list[T]` vs `List[T]`
=> fix: set `3.8` compatible type hints

scripts/collector/oracle/collect-data.sh, scripts/collector/oracle/sql/extracts/eoj.sql, scripts/collector/oracle/sql/op_collect.sql
* Mark the extraction as "error" if the collector session is killed or disconnected from the database.
=> feat: Add "end of job" check for `oracle` 

docs/user_guide/mysql/collection_scripts.md, docs/user_guide/postgres/collection_scripts.md
For homogenous Postgres/mySQL, we need to direct users to upload these collections to MC. Added a comment in the user guide to reflect this
=> docs: Adding comment to user doc for `postgres`/`mysql` to use MC
